{% set name = "fed-rag" %}
{% set version = "0.0.12" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fed_rag-{{ version }}.tar.gz
  sha256: c34c086d9416274fa00ef273f986b9506166ff2a492e9aa1afef4a3a1e4f10be

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0


requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - datasets >=3.1.0
    - flwr >=1.17.0
    - pyarrow >=19.0.1
    - pydantic >=2.10.5
    - pydantic-settings >=2.7.1
    - pytorch >=2.5.1
    - torchvision >=0.20.1
    - typing_extensions >=4.12.2
  run_constrained:
    - libarrow-cuda ==0  # Explicitly constrain against CUDA variants

test:
  imports:
    - fed_rag
  # commands:
  #   - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/fed-rag/
  summary: A framework for federated fine-tuning of retrieval-augmented generation (RAG) systems.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nerdai
